#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Map non-predefined relation types to predefined relation types.

将非预定义的关系类型映射到预定义的关系类型：
- Match：方向一致，直接匹配
- Reverse：方向反转后匹配
- Delete：无法合理匹配（如否定关系、特定数值属性、纯描述性词）

判定原则：
1. 否定关系（not_X / does_not_X / fails_to_X / no_X）一律 Delete；
2. 特定数值/量化属性（has_LD50/has_TAT/has_value_of 等）一律 Delete；
3. 纯描述词或时间性词（duration/time/transient/well_tolerated 等）一律 Delete；
4. 实体名词（activation/infection/intervention 等）映射到对应动词形式（activates/infects/treatment_for）；
5. 过于模糊的关系（used_in/has/undergoes/exerts 等）映射到 associated_with 作为兜底；
6. 不强行匹配/反转，否则使用 associated_with 作为兜底；
7. 预定义关系类型以 Triple_prompt_v2.md 为准，包含 submits（即使其未出现在
   Relationship_instance_statistics_predefined_relation_types.csv 中）。
"""

import argparse
import csv
import sys
from pathlib import Path


# 预定义关系类型集合（依据 Triple_prompt_v2.md，权威来源）
PREDEFINED_RELATIONS = {
    "associated_with", "results_in", "promotes", "activates", "inhibits",
    "increases", "decreases", "exacerbates", "improves", "increases_risk_of",
    "co-occurs_with", "treatment_for", "prevents", "targets", "mediates",
    "positively_correlated_with", "negatively_correlated_with",
    "u_shaped_association_with", "inverted_u_shaped_association_with",
    "includes", "hyponym_of", "abbreviation_for", "help_identify",
    "secretes", "expresses", "binds_to", "differentiates_into",
    "located_in", "induces", "regulates", "produces", "maintains",
    "requires", "disrupts", "reverses", "restores", "stimulates",
    "triggers", "impairs", "infects", "recruits", "limits", "controls",
    "determines", "encodes", "protects", "provides", "reprograms",
    "submits", "eliminates", "phosphorylates", "resistant_to", "delivers",
    "carries", "converts", "depends_on", "decomposes", "neutralizes",
    "replaces", "competes_with", "complements", "enhances", "confers",
    "enters", "explains", "forms", "lacks", "responds_to", "affects",
    "shapes", "similar_to", "stabilizes", "infiltrates", "kills",
    "migrates_to", "polarizes", "prolongs", "recognizes", "changes",
    "defined_as", "distinct_from", "endocytoses", "excludes", "integrates",
    "reaches", "selects", "outperforms", "cooperates_with", "supports",
}


# 非预定义关系 → (matching_manual_type, matching_manual_relation)
RELATION_MAP = {
    # === 频次 >= 5 的高频关系 ===
    "helps_identify": ("Match", "help_identify"),
    "characteristic_of": ("Match", "help_identify"),
    "expressed_by": ("Reverse", "expresses"),
    "decreases_risk_of": ("Match", "prevents"),
    "used_in": ("Match", "associated_with"),
    "reduces": ("Match", "decreases"),
    "modulates": ("Match", "regulates"),
    "marker_for": ("Match", "help_identify"),
    "used_for": ("Match", "associated_with"),
    "model_for": ("Match", "similar_to"),
    "causes": ("Match", "results_in"),
    "upregulates": ("Match", "increases"),
    "suppresses": ("Match", "inhibits"),
    "exhibits": ("Match", "expresses"),
    "expressed_in": ("Reverse", "expresses"),
    "required_for": ("Reverse", "requires"),
    "releases": ("Match", "secretes"),
    "attenuates": ("Match", "decreases"),
    "contains": ("Match", "includes"),
    "alters": ("Match", "changes"),
    "measures": ("Match", "help_identify"),
    "involved_in": ("Match", "associated_with"),
    "contributes_to": ("Match", "promotes"),
    "source_of": ("Match", "produces"),
    "influences": ("Match", "affects"),
    "synergizes_with": ("Match", "cooperates_with"),
    "included_in": ("Reverse", "includes"),
    "superior_to": ("Match", "outperforms"),
    "preserves": ("Match", "maintains"),
    "has_phenotype": ("Reverse", "help_identify"),
    "targeted_by": ("Reverse", "targets"),
    "target_for": ("Reverse", "targets"),
    "modifies": ("Match", "changes"),
    "alleviates": ("Match", "improves"),
    "activated_by": ("Reverse", "activates"),
    "facilitates": ("Match", "promotes"),
    "enables": ("Match", "promotes"),
    "has": ("Match", "associated_with"),
    "expressed_on": ("Reverse", "expresses"),
    "part_of": ("Match", "hyponym_of"),
    "characterized_by": ("Reverse", "help_identify"),
    "undergoes": ("Match", "associated_with"),
    "downregulates": ("Match", "decreases"),
    "necessary_for": ("Reverse", "requires"),
    "mediated_by": ("Reverse", "mediates"),
    "not_associated_with": ("Delete", "No"),
    "does_not_affect": ("Delete", "No"),
    "caused_by": ("Reverse", "results_in"),
    "derived_from": ("Match", "hyponym_of"),
    "predicts": ("Match", "help_identify"),
    "essential_for": ("Reverse", "requires"),
    "interacts_with": ("Match", "binds_to"),
    "uses": ("Match", "associated_with"),
    "enriched_in": ("Match", "located_in"),
    "generates": ("Match", "produces"),
    "protects_against": ("Match", "protects"),
    "ameliorates": ("Match", "improves"),
    "combined_with": ("Match", "cooperates_with"),
    "precedes": ("Match", "outperforms"),
    "exposed_to": ("Match", "associated_with"),
    "represses": ("Match", "inhibits"),
    "detects": ("Match", "help_identify"),
    "potentiates": ("Match", "enhances"),
    "upregulated_in": ("Reverse", "increases"),
    "evaluates": ("Match", "help_identify"),
    "mimics": ("Match", "similar_to"),
    "target_of": ("Reverse", "targets"),
    "validates": ("Match", "help_identify"),
    "blocks": ("Match", "inhibits"),
    "aggravates": ("Match", "exacerbates"),
    "elicits": ("Match", "triggers"),
    "detected_by": ("Reverse", "help_identify"),
    "involves": ("Match", "includes"),
    "increases_for": ("Match", "increases"),
    "drives": ("Match", "promotes"),
    "positively correlated_with": ("Match", "positively_correlated_with"),
    "occurs_in": ("Match", "located_in"),
    "analyzed_by": ("Reverse", "help_identify"),
    "treatment_indication_for": ("Match", "treatment_for"),
    "degrades": ("Match", "decomposes"),
    "reveals": ("Match", "help_identify"),
    "presents": ("Match", "submits"),
    "acts_as": ("Match", "defined_as"),
    "transfers": ("Match", "delivers"),
    "overcomes": ("Match", "outperforms"),
    "differs_from": ("Match", "distinct_from"),
    "independent_of": ("Match", "distinct_from"),
    "differentially_expressed_in": ("Reverse", "expresses"),
    "helps identify": ("Match", "help_identify"),
    "diagnosed_by": ("Reverse", "help_identify"),
    "confirms": ("Match", "help_identify"),
    "utilizes": ("Match", "associated_with"),
    "mitigates": ("Match", "improves"),
    "does_not_improve": ("Delete", "No"),
    "delays": ("Match", "prolongs"),
    "accumulates_in": ("Match", "located_in"),
    "overexpressed_in": ("Reverse", "expresses"),
    "functions_as": ("Match", "defined_as"),
    "measured_by": ("Reverse", "help_identify"),
    "orchestrates": ("Match", "controls"),
    "negatively_regulates": ("Match", "inhibits"),
    "treated_with": ("Reverse", "treatment_for"),
    "down-regulates": ("Match", "decreases"),
    "up-regulates": ("Match", "increases"),
    "clears": ("Match", "eliminates"),
    "initiates": ("Match", "triggers"),
    "validated_by": ("Reverse", "help_identify"),
    "include": ("Match", "includes"),
    "does_not_decrease": ("Delete", "No"),
    "primes": ("Match", "activates"),
    "results_from": ("Reverse", "results_in"),
    "inactivates": ("Match", "inhibits"),
    "cleaves": ("Match", "decomposes"),
    "applied_to": ("Match", "associated_with"),
    "dependent_on": ("Match", "depends_on"),
    "up-regulated_in": ("Reverse", "increases"),
    "impacts": ("Match", "affects"),
    "accelerates": ("Match", "promotes"),
    "inhibited_by": ("Reverse", "inhibits"),
    "transports": ("Match", "delivers"),
    "has_property": ("Match", "associated_with"),
    "synergistic_with": ("Match", "cooperates_with"),
    "achieves": ("Match", "reaches"),
    "reacts_with": ("Match", "binds_to"),
    "restricts": ("Match", "limits"),
    "serves_as": ("Match", "defined_as"),
    "expresses_in": ("Match", "expresses"),
    "promising_therapy_for": ("Match", "treatment_for"),
    "abolishes": ("Match", "eliminates"),
    "reported_in": ("Match", "associated_with"),
    "has_no_effect_on": ("Delete", "No"),
    "overexpresses": ("Match", "expresses"),
    "intervention": ("Match", "treatment_for"),
    "allows": ("Match", "promotes"),
    "regulated_by": ("Reverse", "regulates"),
    "source_for": ("Match", "produces"),
    "combination_with": ("Match", "cooperates_with"),
    "has_increased": ("Match", "increases"),
    "not associated_with": ("Delete", "No"),
    "exerts": ("Match", "associated_with"),
    "compared_with": ("Match", "associated_with"),
    "participates_in": ("Match", "associated_with"),
    "variant_of": ("Match", "hyponym_of"),
    "hydrolyzes": ("Match", "decomposes"),
    "has_cause": ("Reverse", "results_in"),
    "converted_to": ("Reverse", "converts"),
    "promote": ("Match", "promotes"),
    "elevated_in": ("Reverse", "increases"),
    "comparable_to": ("Match", "similar_to"),
    "synergistically_combines_with": ("Match", "cooperates_with"),
    "modulated_by": ("Reverse", "regulates"),
    "has_variant": ("Reverse", "hyponym_of"),
    "has_characteristic": ("Reverse", "help_identify"),
    "activation_rate_mediated_by": ("Reverse", "mediates"),
    "methylation_marker_for": ("Match", "help_identify"),

    # === 频次 = 4 ===
    "component_of": ("Match", "hyponym_of"),
    "takes_up": ("Match", "endocytoses"),
    "not_correlated_with": ("Delete", "No"),
    "demonstrates": ("Match", "help_identify"),
    "increases_in": ("Reverse", "increases"),
    "counteracts": ("Match", "neutralizes"),
    "governs": ("Match", "controls"),
    "optimizes": ("Match", "improves"),
    "characterizes": ("Match", "help_identify"),
    "observed_in": ("Match", "located_in"),
    "arises_from": ("Reverse", "results_in"),
    "has_elevated_level_of": ("Match", "increases"),
    "has_disturbance_in": ("Match", "disrupts"),
    "survives_in": ("Match", "located_in"),
    "does_not_promote": ("Delete", "No"),
    "subject_of": ("Match", "associated_with"),
    "acquires": ("Match", "associated_with"),
    "superior_prognostic_factor_to": ("Match", "outperforms"),
    "infection": ("Match", "infects"),
    "has_better_prognostic_efficacy_than": ("Match", "outperforms"),
    "has_higher_td-AUC_than": ("Match", "outperforms"),
    "occurs_at": ("Match", "located_in"),
    "not_required_for": ("Delete", "No"),
    "produced_by": ("Reverse", "produces"),
    "engulfed_by": ("Reverse", "endocytoses"),
    "infected_with": ("Reverse", "infects"),
    "more_effective_than": ("Match", "outperforms"),
    "reacts_to": ("Match", "responds_to"),
    "is_selective_for": ("Match", "targets"),
    "model_organism_for": ("Match", "similar_to"),
    "metabolizes": ("Match", "decomposes"),
    "colocalizes_with": ("Match", "co-occurs_with"),
    "ineffective_for": ("Delete", "No"),
    "activated_in": ("Reverse", "activates"),
    "critical_for": ("Reverse", "requires"),
    "deposited_in": ("Match", "located_in"),
    "codes_for": ("Match", "encodes"),
    "has_population_coverage": ("Delete", "No"),
    "conserved_in": ("Match", "associated_with"),
    "intervention_for": ("Match", "treatment_for"),
    "is_a": ("Match", "hyponym_of"),
    "infection_with": ("Reverse", "infects"),

    # === 频次 = 3 ===
    "shifts": ("Match", "changes"),
    "prognostic_factor_for": ("Match", "help_identify"),
    "favors": ("Match", "promotes"),
    "studied_in": ("Match", "associated_with"),
    "based_on": ("Match", "depends_on"),
    "duration_of": ("Delete", "No"),
    "does_not_increase": ("Delete", "No"),
    "has_sensitivity": ("Delete", "No"),
    "has_specificity": ("Delete", "No"),
    "immunoreactive_for": ("Match", "responds_to"),
    "calculates": ("Match", "help_identify"),
    "mobilizes": ("Match", "recruits"),
    "affected_by": ("Reverse", "affects"),
    "antigen_for": ("Reverse", "recognizes"),
    "present_in": ("Match", "located_in"),
    "fails_to_induce": ("Delete", "No"),
    "bind_to": ("Match", "binds_to"),
    "elevates": ("Match", "increases"),
    "compared_to": ("Match", "associated_with"),
    "decreased_by": ("Reverse", "decreases"),
    "used_as": ("Match", "associated_with"),
    "has_disruption_in": ("Match", "disrupts"),
    "has_activation_of": ("Match", "activates"),
    "scavenges": ("Match", "eliminates"),
    "helps": ("Match", "associated_with"),
    "maintained_by": ("Reverse", "maintains"),
    "retained_in": ("Match", "located_in"),
    "crosstalk_with": ("Match", "cooperates_with"),
    "suppressed_by": ("Reverse", "inhibits"),
    "proliferates_in": ("Match", "located_in"),
    "classifies": ("Match", "help_identify"),
    "does_not_express": ("Delete", "No"),
    "has_rebound": ("Delete", "No"),
    "target": ("Match", "targets"),
    "followed_by": ("Match", "outperforms"),
    "targets_for": ("Match", "targets"),
    "overactivated_in": ("Reverse", "activates"),
    "guides": ("Match", "controls"),
    "boosts": ("Match", "enhances"),
    "stimulated_by": ("Reverse", "stimulates"),
    "reduces_risk_of": ("Match", "prevents"),
    "recommended_for": ("Match", "treatment_for"),
    "tested_for": ("Match", "associated_with"),
    "augments": ("Match", "enhances"),
    "delivered_by": ("Reverse", "delivers"),
    "hijacks": ("Match", "controls"),
    "potential treatment_for": ("Match", "treatment_for"),
    "potential_therapeutic_target_for": ("Match", "associated_with"),
    "does_not_prevent": ("Delete", "No"),
    "has_antifungal_activity_against": ("Match", "inhibits"),
    "developed_into": ("Match", "differentiates_into"),
    "treatment_target_for": ("Match", "associated_with"),
    "re-activates": ("Match", "activates"),
    "validated_for": ("Reverse", "help_identify"),
    "spreads_to": ("Match", "migrates_to"),
    "recapitulates": ("Match", "similar_to"),
    "encoded_by": ("Reverse", "encodes"),
    "has_predictivity": ("Match", "help_identify"),
    "administered_via": ("Match", "associated_with"),
    "regulated_via": ("Reverse", "regulates"),
    "not_expresses": ("Delete", "No"),
    "challenged_by": ("Match", "associated_with"),
    "not_involved_in": ("Delete", "No"),
    "deregulation": ("Match", "disrupts"),
    "protects against": ("Match", "protects"),
    "diagnostic_for": ("Match", "help_identify"),
    "ubiquitinates": ("Match", "changes"),
    "shows": ("Match", "associated_with"),
    "belongs_to": ("Match", "hyponym_of"),
    "streamlines": ("Match", "improves"),
    "migrates_through": ("Match", "migrates_to"),
    "evaluated_in": ("Reverse", "help_identify"),
    "hypomethylated_in": ("Delete", "No"),
    "has_methylation_changes_in_promoter": ("Match", "changes"),
    "harbors": ("Match", "includes"),
    "conducted_in": ("Match", "associated_with"),
    "has_elevated_markers_of": ("Match", "help_identify"),
    "produced_in": ("Reverse", "produces"),
    "internalizes": ("Match", "endocytoses"),
    "isolates": ("Match", "selects"),
    "dysregulates": ("Match", "disrupts"),
    "fuses_with": ("Match", "integrates"),
    "acts_via": ("Match", "associated_with"),
    "effective_in": ("Match", "treatment_for"),
    "does_not_require": ("Delete", "No"),
    "analysis_for": ("Match", "associated_with"),
    "isolated_from": ("Match", "hyponym_of"),
    "occurred_in": ("Match", "located_in"),
    "distinguishes": ("Match", "help_identify"),
    "has_metastasis_in": ("Match", "migrates_to"),
    "application_for": ("Match", "associated_with"),
    "loss_of_function": ("Match", "impairs"),
    "infection_by": ("Reverse", "infects"),
    "replicates_in": ("Match", "located_in"),
    "differentiated_into": ("Match", "differentiates_into"),

    # === 频次 = 2 ===
    "incorporated_into": ("Match", "integrates"),
    "contains_abundant_uracils": ("Match", "includes"),
    "translocates_to": ("Match", "migrates_to"),
    "lacks_expression_of": ("Match", "lacks"),
    "used_with": ("Match", "associated_with"),
    "expands_during": ("Match", "associated_with"),
    "metastasizes_to": ("Match", "migrates_to"),
    "important_for": ("Reverse", "requires"),
    "potential_target_for": ("Reverse", "targets"),
    "risk_factor_for": ("Match", "increases_risk_of"),
    "analyzes": ("Match", "help_identify"),
    "infected_by": ("Reverse", "infects"),
    "encapsulates": ("Match", "includes"),
    "negates": ("Match", "neutralizes"),
    "causative_agent_of": ("Match", "results_in"),
    "method_for": ("Match", "help_identify"),
    "signals_via": ("Match", "associated_with"),
    "assesses": ("Match", "help_identify"),
    "examines": ("Match", "help_identify"),
    "occurs_within": ("Match", "located_in"),
    "abrogates": ("Match", "eliminates"),
    "sensitive_to": ("Match", "responds_to"),
    "towards": ("Match", "associated_with"),
    "performs_better_in": ("Match", "associated_with"),
    "precursor_of": ("Match", "differentiates_into"),
    "connects": ("Match", "associated_with"),
    "treated_as": ("Match", "associated_with"),
    "used_to_model": ("Match", "associated_with"),
    "stable_at_different_temperatures_and_pH": ("Delete", "No"),
    "transmits": ("Match", "delivers"),
    "more effective than": ("Match", "outperforms"),
    "has_target": ("Match", "targets"),
    "has_TAT": ("Delete", "No"),
    "more_sensitive_in": ("Match", "outperforms"),
    "arrests": ("Match", "inhibits"),
    "underlies": ("Match", "supports"),
    "increase": ("Match", "increases"),
    "constitutes": ("Match", "hyponym_of"),
    "is_required_for": ("Reverse", "requires"),
    "redirects": ("Match", "changes"),
    "more_likely_in": ("Reverse", "increases_risk_of"),
    "creates": ("Match", "produces"),
    "models": ("Match", "similar_to"),
    "uptake_by": ("Reverse", "endocytoses"),
    "recruited_by": ("Reverse", "recruits"),
    "performed_by": ("Match", "associated_with"),
    "inserted_into": ("Match", "integrates"),
    "delivered_via": ("Reverse", "delivers"),
    "duration": ("Delete", "No"),
    "minimizes": ("Match", "decreases"),
    "presented_by": ("Reverse", "submits"),
    "egresses_from": ("Delete", "No"),
    "defines": ("Reverse", "defined_as"),
    "partially prevents": ("Match", "prevents"),
    "indication_for": ("Match", "treatment_for"),
    "identifies": ("Match", "help_identify"),
    "taken_up_by": ("Reverse", "endocytoses"),
    "lasts_up_to": ("Delete", "No"),
    "has_low_cytotoxicity": ("Delete", "No"),
    "does_not_change": ("Delete", "No"),
    "characterised_by": ("Reverse", "help_identify"),
    "is": ("Match", "defined_as"),
    "prepared_by": ("Reverse", "produces"),
    "increases_sensitivity_of": ("Match", "enhances"),
    "retards": ("Match", "inhibits"),
    "synthesized_by": ("Reverse", "produces"),
    "has_superior_predictive_accuracy_than": ("Match", "outperforms"),
    "establishes": ("Match", "produces"),
    "has_higher_expression_of": ("Match", "expresses"),
    "validated_in": ("Reverse", "help_identify"),
    "crosslinks": ("Match", "binds_to"),
    "has_higher_affinity_than": ("Match", "outperforms"),
    "challenge_for": ("Match", "associated_with"),
    "released_by": ("Reverse", "secretes"),
    "composed_of": ("Reverse", "hyponym_of"),
    "has_negative_predictive_value": ("Delete", "No"),
    "internalized_by": ("Reverse", "endocytoses"),
    "potential_modulator_of": ("Match", "regulates"),
    "predominates_in": ("Match", "located_in"),
    "displaces": ("Match", "replaces"),
    "senses": ("Match", "recognizes"),
    "decreases_toxicity_towards": ("Match", "protects"),
    "accounts_for_percentage_of": ("Match", "hyponym_of"),
    "has_low_incidence_rate": ("Delete", "No"),
    "isolated_by": ("Reverse", "selects"),
    "retains": ("Match", "maintains"),
    "substrate_of": ("Reverse", "decomposes"),
    "not internalized_by": ("Delete", "No"),
    "expressed_more_than": ("Match", "outperforms"),
    "transferred_via": ("Match", "delivers"),
    "function_as": ("Match", "defined_as"),
    "limited_by": ("Reverse", "limits"),
    "preferred_for": ("Match", "treatment_for"),
    "not_indicated_for": ("Delete", "No"),
    "potential_treatment_for": ("Match", "treatment_for"),
    "rich_in": ("Match", "includes"),
    "leads_to": ("Match", "results_in"),
    "assessed_by": ("Reverse", "help_identify"),
    "surpasses": ("Match", "outperforms"),
    "valid_for": ("Match", "associated_with"),
    "is_not_toxic_to": ("Delete", "No"),
    "used_in_model_for": ("Match", "associated_with"),
    "rebalances": ("Match", "restores"),
    "highly_expressing": ("Match", "expresses"),
    "induced_by": ("Reverse", "induces"),
    "contacts": ("Match", "binds_to"),
    "hypermethylated_in": ("Delete", "No"),
    "does_not_help_identify": ("Delete", "No"),
    "has_higher_IL-6_than": ("Delete", "No"),
    "independent predictive factor for": ("Match", "help_identify"),
    "evaluated_on": ("Reverse", "help_identify"),
    "key_mediator_of": ("Match", "mediates"),
    "remodels": ("Match", "reprograms"),
    "develops": ("Match", "associated_with"),
    "depresses": ("Match", "decreases"),
    "synergistically suppresses": ("Match", "inhibits"),
    "synthesizes": ("Match", "produces"),
    "has_higher_affinity_for": ("Match", "binds_to"),
    "defined_by": ("Reverse", "defined_as"),
    "host_for": ("Reverse", "infects"),
    "negative_for": ("Match", "lacks"),
    "performed_in": ("Match", "associated_with"),
    "has_absolute_bioavailability": ("Delete", "No"),
    "bypasses": ("Match", "associated_with"),
    "has_symptom": ("Reverse", "help_identify"),
    "correlated_with": ("Match", "associated_with"),
    "more_sensitive_than": ("Match", "outperforms"),
    "transmitted_by": ("Reverse", "delivers"),
    "provokes": ("Match", "triggers"),
    "is_essential_for": ("Reverse", "requires"),
    "encompasses": ("Match", "includes"),
    "challenges": ("Match", "associated_with"),
    "does_not_recapitulate": ("Delete", "No"),
    "common_name": ("Match", "abbreviation_for"),
    "has_high_selectivity_index": ("Delete", "No"),
    "oligomerizes_into": ("Match", "forms"),
    "has_value_of": ("Delete", "No"),
    "extracted_from": ("Match", "hyponym_of"),
    "synergistically_induces": ("Match", "induces"),
    "excluded_from": ("Reverse", "excludes"),
    "occurs_during": ("Delete", "No"),
    "used_in_preparation_of": ("Match", "produces"),
    "provides energy for": ("Match", "provides"),
    "implemented_in": ("Match", "located_in"),
    "disturbs": ("Match", "disrupts"),
    "observed_at": ("Match", "associated_with"),
    "transmitted_via": ("Match", "delivers"),
    "presents_antigen_to": ("Match", "submits"),
    "candidate_for": ("Match", "treatment_for"),
    "does_not_block": ("Delete", "No"),
    "control_for": ("Match", "associated_with"),
    "has_time_phase": ("Delete", "No"),
    "is_sensitive_to": ("Match", "responds_to"),
    "experiences": ("Match", "associated_with"),
    "is_compartments_of": ("Match", "hyponym_of"),
    "more_sensitive_to": ("Match", "responds_to"),
    "shared_by": ("Match", "associated_with"),
    "has_adverse_outcome": ("Match", "results_in"),
    "uptake_of": ("Match", "endocytoses"),
    "anchors": ("Match", "binds_to"),
    "underpins": ("Match", "supports"),
    "does_not_reduce": ("Delete", "No"),
    "depletes": ("Match", "decreases"),
    "accompanies": ("Match", "co-occurs_with"),
    "expands": ("Match", "increases"),
    "eradicates": ("Match", "eliminates"),
    "non-cytotoxic_to": ("Delete", "No"),
    "sufficient_for": ("Match", "promotes"),
    "enriched_at": ("Match", "located_in"),
    "study_population_for": ("Match", "associated_with"),
    "outcome_measured_by": ("Reverse", "help_identify"),
    "has_high_resistance_rate": ("Delete", "No"),
    "used_to_form": ("Match", "produces"),
    "used_to_analyze": ("Match", "help_identify"),
    "used_to_visualize": ("Match", "help_identify"),
    "halts": ("Match", "inhibits"),
    "reestablishes": ("Match", "restores"),
    "has_LoB": ("Delete", "No"),
    "has_LoD": ("Delete", "No"),
    "detected_in": ("Match", "located_in"),
    "ablates": ("Match", "eliminates"),
    "reinvigorates": ("Match", "restores"),
    "has_part": ("Match", "includes"),
    "indicates": ("Match", "help_identify"),
    "upregulated_by": ("Reverse", "increases"),
    "slows": ("Match", "inhibits"),
    "serves_as_scaffold_for": ("Match", "supports"),
    "diagnosed_in": ("Reverse", "help_identify"),
    "has_higher_digestibility_than": ("Match", "outperforms"),
    "implicated_in": ("Match", "associated_with"),
    "infiltrates_in": ("Match", "infiltrates"),
    "used_in_study_of": ("Match", "associated_with"),
    "stable_for": ("Delete", "No"),
    "positively_regulates": ("Match", "promotes"),

    # === 频次 = 1 ===
    "diverts_to": ("Match", "migrates_to"),
    "used_on": ("Match", "associated_with"),
    "not_applicable_to": ("Delete", "No"),
    "more_effective_in": ("Match", "outperforms"),
    "corroborates": ("Match", "supports"),
    "adverse_effect_of": ("Reverse", "results_in"),
    "quenches": ("Match", "inhibits"),
    "cost-effective_at": ("Delete", "No"),
    "has_plasma_stability": ("Delete", "No"),
    "tolerated_at_dose": ("Delete", "No"),
    "no_effect_on": ("Delete", "No"),
    "partial_target_engagement_in": ("Match", "targets"),
    "sheds": ("Match", "secretes"),
    "engaged_by": ("Reverse", "binds_to"),
    "phosphorylated": ("Delete", "No"),
    "differentiates": ("Match", "differentiates_into"),
    "analyzed_for": ("Reverse", "help_identify"),
    "intended_to_improve": ("Match", "improves"),
    "reciprocal_with": ("Match", "cooperates_with"),
    "impedes": ("Match", "inhibits"),
    "approximates": ("Match", "similar_to"),
    "exerts_direct_effects_on": ("Match", "affects"),
    "tested_in": ("Match", "associated_with"),
    "persists": ("Delete", "No"),
    "polyfunctional": ("Delete", "No"),
    "persists_indefinitely": ("Delete", "No"),
    "avoids": ("Match", "associated_with"),
    "manipulates": ("Match", "regulates"),
    "reshapes": ("Match", "reprograms"),
    "detached_under_pathological_conditions": ("Delete", "No"),
    "distributed_via": ("Match", "associated_with"),
    "capable_of": ("Match", "associated_with"),
    "spared_by": ("Match", "associated_with"),
    "differed_between": ("Match", "associated_with"),
    "predisposing_factor_for": ("Match", "increases_risk_of"),
    "undergo": ("Match", "associated_with"),
    "optimal_for": ("Match", "treatment_for"),
    "limitation_of": ("Reverse", "limits"),
    "has_cytotoxic_effect_on": ("Match", "kills"),
    "barrier_to": ("Match", "inhibits"),
    "structure_assigned_via": ("Reverse", "help_identify"),
    "influenced_by": ("Reverse", "affects"),
    "less_inhibited_by": ("Match", "associated_with"),
    "highly_dependent_on": ("Match", "depends_on"),
    "describes": ("Match", "associated_with"),
    "can_be_used_for": ("Match", "associated_with"),
    "has_LD50": ("Delete", "No"),
    "works_additively_with": ("Match", "cooperates_with"),
    "not_pathogenic_to": ("Delete", "No"),
    "not_cost_effective_at": ("Delete", "No"),
    "does_not_explain": ("Delete", "No"),
    "impacts_on": ("Match", "affects"),
    "is_candidate_for": ("Match", "treatment_for"),
    "plays critical role in": ("Match", "associated_with"),
    "vaccine_candidate_for": ("Match", "treatment_for"),
    "are_highly_conserved_among": ("Match", "associated_with"),
    "disturbed_by": ("Reverse", "disrupts"),
    "potential_as": ("Match", "associated_with"),
    "calculated_for": ("Match", "associated_with"),
    "ranges_from": ("Delete", "No"),
    "ranges_to": ("Delete", "No"),
    "should_account_for": ("Match", "associated_with"),
    "fails_to_improve": ("Delete", "No"),
    "substrate_for": ("Reverse", "decomposes"),
    "adapts_to": ("Match", "responds_to"),
    "weak_in": ("Delete", "No"),
    "performed_on": ("Match", "associated_with"),
    "has_limited_cross-neutralization_against": ("Delete", "No"),
    "has stronger anti-inflammatory effect than": ("Match", "outperforms"),
    "negatively correlated_with": ("Match", "negatively_correlated_with"),
    "carrier_of": ("Match", "carries"),
    "has_enriched_pathway": ("Match", "includes"),
    "has_increased_population": ("Match", "increases"),
    "has_decreased": ("Match", "decreases"),
    "has_greater_impact_on": ("Match", "affects"),
    "infection_induces": ("Match", "induces"),
    "meets_criterion": ("Match", "associated_with"),
    "has_no_change_in": ("Delete", "No"),
    "synthesized_in": ("Reverse", "produces"),
    "exported_through": ("Match", "associated_with"),
    "has_effect_on": ("Match", "affects"),
    "transported_by": ("Reverse", "delivers"),
    "down_regulates": ("Match", "decreases"),
    "exhibits_rhythm_in": ("Match", "associated_with"),
    "has_cutoff_value": ("Delete", "No"),
    "diagnostic_accuracy": ("Delete", "No"),
    "resembles": ("Match", "similar_to"),
    "secreted_by": ("Reverse", "secretes"),
    "co-labeled_with": ("Match", "co-occurs_with"),
    "respond_to": ("Match", "responds_to"),
    "transition_to": ("Match", "differentiates_into"),
    "expresses_on": ("Match", "expresses"),
    "has_better_antimicrobial_activity_than": ("Match", "outperforms"),
    "integrates_via": ("Match", "integrates"),
    "has_low": ("Delete", "No"),
    "located_on": ("Match", "located_in"),
    "transfects": ("Match", "associated_with"),
    "is_independent_of": ("Match", "distinct_from"),
    "initializes": ("Match", "triggers"),
    "used_in_study_for": ("Match", "associated_with"),
    "critical_element_in": ("Reverse", "requires"),
    "trained_on": ("Match", "associated_with"),
    "concordant_with": ("Match", "similar_to"),
    "engulfs": ("Match", "endocytoses"),
    "does_not_enhance": ("Delete", "No"),
    "has_higher_sensitivity_for": ("Match", "outperforms"),
    "focuses_on": ("Match", "associated_with"),
    "engages": ("Match", "binds_to"),
    "occurs_after": ("Delete", "No"),
    "has_duration": ("Delete", "No"),
    "assembly_time": ("Delete", "No"),
    "coupled_to": ("Match", "binds_to"),
    "has_high_metastatic_potential": ("Delete", "No"),
    "lacks_effective_therapies": ("Delete", "No"),
    "efficacy_affected_by": ("Reverse", "affects"),
    "has_no_similarity_with": ("Delete", "No"),
    "has_higher_AUC_than": ("Match", "outperforms"),
    "infection_causes": ("Match", "results_in"),
    "confers protection against": ("Match", "protects"),
    "causes_cytotoxicity": ("Match", "kills"),
    "electroporated_with": ("Match", "associated_with"),
    "lyses": ("Match", "kills"),
    "immunogenic_in": ("Match", "associated_with"),
    "has_better_performance_than": ("Match", "outperforms"),
    "enhances_inhibition_of": ("Match", "inhibits"),
    "does_not_bind_to": ("Delete", "No"),
    "retains_ability_to": ("Match", "associated_with"),
    "has_retention_in": ("Match", "located_in"),
    "not improves": ("Delete", "No"),
    "sorts": ("Match", "selects"),
    "activation": ("Match", "activates"),
    "preferred_in": ("Match", "treatment_for"),
    "has_similar_recovery_to": ("Match", "similar_to"),
    "transplanted_into": ("Match", "enters"),
    "anti-inflammatory": ("Delete", "No"),
    "matures_to": ("Match", "differentiates_into"),
    "loses_interaction_with": ("Match", "associated_with"),
    "dose_dependently_inhibits": ("Match", "inhibits"),
    "exerts_long_term_effects_via": ("Match", "associated_with"),
    "does_not_alleviate": ("Delete", "No"),
    "transient": ("Delete", "No"),
    "adopts": ("Match", "associated_with"),
    "fusion_with": ("Match", "integrates"),
    "remains_seronegative_for": ("Delete", "No"),
    "presented_to": ("Match", "submits"),
    "are": ("Match", "defined_as"),
    "mirrors": ("Match", "similar_to"),
    "not_related_to": ("Delete", "No"),
    "hosts": ("Reverse", "infects"),
    "tropism_for": ("Match", "targets"),
    "bridges": ("Match", "binds_to"),
    "stimulated_with": ("Reverse", "stimulates"),
    "has_outcome": ("Match", "results_in"),
    "administered_in": ("Match", "associated_with"),
    "transmission_via": ("Match", "delivers"),
    "ensures": ("Match", "maintains"),
    "directs": ("Match", "controls"),
    "contact_with": ("Match", "binds_to"),
    "envelops": ("Match", "includes"),
    "translocated_by": ("Reverse", "delivers"),
    "builds": ("Match", "produces"),
    "verifies": ("Match", "help_identify"),
    "degraded_into": ("Reverse", "converts"),
    "weakens": ("Match", "decreases"),
    "rescues": ("Match", "restores"),
    "preferred_indication_for": ("Match", "treatment_for"),
    "take_up": ("Match", "endocytoses"),
    "homodimerizes": ("Match", "forms"),
    "not_expressed_in": ("Delete", "No"),
    "receives_input_from": ("Reverse", "provides"),
    "projects_to": ("Match", "migrates_to"),
    "separates": ("Match", "selects"),
    "has_purity": ("Delete", "No"),
    "fails_to_discriminate": ("Delete", "No"),
    "originates_from": ("Match", "hyponym_of"),
    "catalyzes": ("Match", "promotes"),
    "categorised_as": ("Match", "defined_as"),
    "does_not_internalize": ("Delete", "No"),
    "has_potential_to_escape": ("Match", "associated_with"),
    "does_not_co-occur_with": ("Delete", "No"),
    "not mediates": ("Delete", "No"),
    "does_not_develop": ("Delete", "No"),
    "triggered_by": ("Reverse", "triggers"),
    "has_lower_number_of_non-responders": ("Delete", "No"),
    "using_crude_sweat": ("Delete", "No"),
    "alternative_tool_for": ("Match", "associated_with"),
    "deregulates": ("Match", "disrupts"),
    "enrolls": ("Match", "associated_with"),
    "acts_on": ("Match", "affects"),
    "similar_distribution_to": ("Match", "similar_to"),
    "hypothesized_common_target_with": ("Match", "associated_with"),
    "hypothesized_similar_target_profile_to": ("Match", "associated_with"),
    "does_not_distinguish": ("Delete", "No"),
    "autoregulates": ("Match", "regulates"),
    "substitute_for": ("Match", "replaces"),
    "dephosphorylates": ("Match", "changes"),
    "has_pharmacokinetics": ("Delete", "No"),
    "role_in": ("Match", "associated_with"),
    "enriches_for": ("Match", "increases"),
    "has_little_impact_on": ("Delete", "No"),
    "recruited_to": ("Reverse", "recruits"),
    "does_not_influence": ("Delete", "No"),
    "increases_vulnerability_to": ("Match", "increases_risk_of"),
    "enters_via": ("Match", "enters"),
    "has_lower_IC50_than": ("Match", "outperforms"),
    "moderates": ("Match", "regulates"),
    "occurs_more_frequently_in": ("Reverse", "increases_risk_of"),
    "more immunogenic than": ("Match", "outperforms"),
    "master_regulator_of": ("Match", "regulates"),
    "molecular_vulnerability_of": ("Match", "associated_with"),
    "causative_agent_for": ("Match", "results_in"),
    "has_reservoir_of": ("Match", "includes"),
    "has_higher_frequency_of": ("Match", "increases"),
    "has_more_limited_frequency_and_diversity_in": ("Delete", "No"),
    "decreases_over_time": ("Delete", "No"),
    "under_selection_pressure_from": ("Reverse", "selects"),
    "has_reproducibility": ("Delete", "No"),
    "are_valuable_prognostic_indicators": ("Match", "help_identify"),
    "higher_in": ("Reverse", "increases"),
    "synergistically_regulate": ("Match", "regulates"),
    "practiced_by": ("Match", "associated_with"),
    "exchanges": ("Match", "associated_with"),
    "exhibit": ("Match", "expresses"),
    "main_driver_of": ("Match", "promotes"),
    "conjugates_with": ("Match", "binds_to"),
    "purified_by": ("Reverse", "selects"),
    "stability_evaluated_in": ("Match", "associated_with"),
    "transmigrates_into": ("Match", "migrates_to"),
    "deficient_in": ("Reverse", "lacks"),
    "lipid raft-mediated": ("Delete", "No"),
    "endocytosis_in": ("Match", "associated_with"),
    "has_higher_bioavailability_than": ("Match", "outperforms"),
    "transfected_with": ("Match", "associated_with"),
    "regresses": ("Match", "decreases"),
    "isolated_in": ("Match", "located_in"),
    "genotype": ("Match", "associated_with"),
    "negatively regulates": ("Match", "inhibits"),
    "ingests": ("Match", "endocytoses"),
    "used_to_assess": ("Match", "help_identify"),
    "used_to_compare": ("Match", "associated_with"),
    "permits": ("Match", "promotes"),
    "produced_from": ("Reverse", "produces"),
    "increases_availability_for": ("Match", "provides"),
    "improves_ability_to_slow": ("Match", "enhances"),
    "has_cure_rate": ("Delete", "No"),
    "extracts": ("Match", "produces"),
    "suitable_for": ("Match", "associated_with"),
    "hinders": ("Match", "inhibits"),
    "inhibition_results_in": ("Match", "associated_with"),
    "destroys": ("Match", "eliminates"),
    "signaling": ("Match", "associated_with"),
    "essential for": ("Reverse", "requires"),
    "not_sufficient_to": ("Delete", "No"),
    "associates_with": ("Match", "associated_with"),
    "cultured_with": ("Match", "associated_with"),
    "not_sufficient_for": ("Delete", "No"),
    "defends_against": ("Match", "protects"),
    "protected_from": ("Reverse", "protects"),
    "peaks_at": ("Delete", "No"),
    "provides resistance against": ("Match", "protects"),
    "occurrence": ("Match", "associated_with"),
    "different_from": ("Match", "distinct_from"),
    "does_not_differentiate_into": ("Delete", "No"),
    "reversible": ("Delete", "No"),
    "complication_of": ("Reverse", "results_in"),
    "does_not_provide": ("Delete", "No"),
    "cross-neutralizes": ("Match", "neutralizes"),
    "infests": ("Match", "infects"),
    "dilated_by": ("Reverse", "increases"),
    "has_limitation": ("Delete", "No"),
    "stable_in": ("Match", "located_in"),
    "uptake": ("Match", "endocytoses"),
    "poorly_immunogenetic": ("Delete", "No"),
    "transduced_with": ("Match", "associated_with"),
    "not_binds_to": ("Delete", "No"),
    "skewed_towards": ("Match", "polarizes"),
    "offers_therapeutic_potential_for": ("Match", "treatment_for"),
    "adversely_affects": ("Match", "impairs"),
    "incompletely_prevents": ("Match", "prevents"),
    "diverts": ("Match", "changes"),
    "work_in_concert": ("Match", "cooperates_with"),
    "helps_fix": ("Match", "associated_with"),
    "compromises": ("Match", "impairs"),
    "has_low_concentration_in": ("Delete", "No"),
    "has_similar": ("Match", "similar_to"),
    "estimated_by": ("Reverse", "help_identify"),
    "accumulates_toward": ("Match", "migrates_to"),
    "rearranges": ("Match", "changes"),
    "not_prevents": ("Delete", "No"),
    "acetylates": ("Match", "changes"),
    "acetylated_at": ("Reverse", "changes"),
    "abnormal_in": ("Match", "associated_with"),
    "have longer": ("Match", "prolongs"),
    "dysregulated_in": ("Match", "associated_with"),
    "has_anatomy": ("Match", "located_in"),
    "attached_to": ("Match", "binds_to"),
    "occludes": ("Match", "inhibits"),
    "has_lower_activation_energy_barrier_for": ("Match", "outperforms"),
    "disinhibits": ("Match", "activates"),
    "does_not_elicit": ("Delete", "No"),
    "well_tolerated": ("Delete", "No"),
    "reinforces": ("Match", "enhances"),
    "relevant_to_therapy_for": ("Match", "associated_with"),
    "relevant_to": ("Match", "associated_with"),
    "overexpression_of": ("Match", "expresses"),
    "reduced_activation_of": ("Match", "inhibits"),
    "has_higher_C_index_than": ("Match", "outperforms"),
    "has_higher_IL-5_than": ("Delete", "No"),
    "not_sufficient_as": ("Delete", "No"),
    "not_recommended_for": ("Delete", "No"),
    "is_transient": ("Delete", "No"),
    "migrates_into": ("Match", "migrates_to"),
    "plays_pivotal_role_in": ("Match", "associated_with"),
    "short duration": ("Delete", "No"),
    "couples": ("Match", "binds_to"),
    "insufficient_alone": ("Delete", "No"),
    "promising_for": ("Match", "treatment_for"),
    "is_casted_in": ("Match", "associated_with"),
    "benchmark_for": ("Match", "associated_with"),
    "differentially_impacts": ("Match", "affects"),
    "compensates_for": ("Match", "replaces"),
    "rewires": ("Match", "reprograms"),
    "plays_indirect_role_in": ("Match", "associated_with"),
    "planned_for": ("Match", "associated_with"),
    "identified_as": ("Match", "defined_as"),
    "works synergistically with": ("Match", "cooperates_with"),
    "timing_for": ("Delete", "No"),
    "degrades_in": ("Match", "associated_with"),
    "has_role_in": ("Match", "associated_with"),
    "has_activity": ("Delete", "No"),
    "prefers": ("Match", "selects"),
    "induced_under": ("Reverse", "induces"),
    "speeds_up": ("Match", "promotes"),
    "needs_to_reach": ("Match", "reaches"),
    "deficiency_results_in": ("Delete", "No"),
    "has_vaccine_candidate": ("Reverse", "treatment_for"),
    "stable_over_time": ("Delete", "No"),
    "overexpression": ("Match", "expresses"),
    "maintained_for": ("Delete", "No"),
    "improved_by": ("Reverse", "improves"),
    "unresponsive_to": ("Delete", "No"),
    "sensitizes": ("Match", "enhances"),
    "present_to": ("Match", "submits"),
    "less_effective_than": ("Reverse", "outperforms"),
    "time": ("Delete", "No"),
    "has_absolute_oral_bioavailability": ("Delete", "No"),
    "plays_redundant_role_in": ("Match", "associated_with"),
    "metabolized_to": ("Match", "converts"),
    "has_lower_KD_value_for": ("Match", "outperforms"),
    "has_lower_IC₅₀_value_for": ("Match", "outperforms"),
    "synergizes_to_up-regulate": ("Match", "increases"),
    "alternative_to": ("Match", "replaces"),
    "inversely_correlated_with": ("Match", "negatively_correlated_with"),
    "bridges_to": ("Match", "binds_to"),
    "cleaved_by": ("Reverse", "decomposes"),
    "has_chaperone_activity": ("Delete", "No"),
    "rationale_for": ("Match", "explains"),
    "expressed_under": ("Reverse", "expresses"),
    "targetable_by": ("Reverse", "targets"),
    "worsens": ("Match", "exacerbates"),
    "uptaken_by": ("Reverse", "endocytoses"),
    "has M2 macrophage-like ability": ("Delete", "No"),
    "signals_for": ("Match", "triggers"),
    "increases_susceptibility_to": ("Match", "increases_risk_of"),
    "negatively_associated_with": ("Match", "negatively_correlated_with"),
    "has_protein": ("Match", "expresses"),
    "carried_by": ("Reverse", "carries"),
    "contained_in": ("Reverse", "includes"),
    "cocultured_with": ("Match", "associated_with"),
    "peaks_in": ("Delete", "No"),
    "source": ("Match", "produces"),
    "has_orthologue": ("Match", "similar_to"),
    "more_active_than": ("Match", "outperforms"),
    "inactivated_by": ("Reverse", "inhibits"),
    "personalises": ("Match", "associated_with"),
    "has_high_selectivity_for": ("Match", "targets"),
    "fails_to_detect": ("Delete", "No"),
    "higher_than": ("Match", "outperforms"),
    "delayed_in": ("Match", "associated_with"),
    "marginally_influences": ("Match", "affects"),
    "modified_with": ("Reverse", "changes"),
    "has_higher_value_of": ("Match", "outperforms"),
    "has_higher_mass_fraction_in_plasma_than": ("Match", "outperforms"),
    "dysregulated_into": ("Match", "disrupts"),
    "inferred_for": ("Match", "associated_with"),
    "phagocytoses": ("Match", "endocytoses"),
    "has_potential_for": ("Match", "associated_with"),
    "armed_with": ("Match", "includes"),
    "co-delivered_with": ("Match", "cooperates_with"),
    "reinforced_with": ("Reverse", "enhances"),
    "is_target_for": ("Reverse", "targets"),
    "rejects": ("Match", "associated_with"),
    "hampered": ("Delete", "No"),
    "increases_dependency_on": ("Match", "associated_with"),
    "more accurate than": ("Match", "outperforms"),
    "independently prognostic_of": ("Match", "help_identify"),
    "has_higher_catalytic_efficiency_than": ("Match", "outperforms"),
    "primarily_responsible_for": ("Match", "results_in"),
    "differentiate_into": ("Match", "differentiates_into"),
    "site_of": ("Reverse", "located_in"),
    "dephosphorylated_at": ("Reverse", "changes"),
    "is lactylated": ("Delete", "No"),
    "undergoes_transition_to": ("Match", "differentiates_into"),
    "is inhibited_by": ("Reverse", "inhibits"),
    "used_in_expansion_of": ("Match", "promotes"),
    "relocates_to": ("Match", "migrates_to"),
    "coordinates": ("Match", "controls"),
    "serves_as_platform_for": ("Match", "supports"),
    "expressed on": ("Reverse", "expresses"),
    "encapsulated_with": ("Reverse", "includes"),
    "model_in": ("Match", "associated_with"),
    "rearranged_by": ("Reverse", "changes"),
    "increases_effectiveness_of": ("Match", "enhances"),
    "target_population_for": ("Reverse", "treatment_for"),
    "weakly impairs": ("Match", "impairs"),
    "translocated_to": ("Match", "migrates_to"),
    "has_few": ("Delete", "No"),
    "has_etiology": ("Reverse", "results_in"),
    "anchored_by": ("Reverse", "binds_to"),
    "exemplifies": ("Match", "hyponym_of"),
    "is_modified_by": ("Reverse", "changes"),
    "variant": ("Match", "hyponym_of"),
    "species_of": ("Reverse", "hyponym_of"),
    "has_gene": ("Match", "includes"),
    "oxidized_by": ("Reverse", "changes"),
    "functionally_replaces": ("Match", "replaces"),
    "has_high": ("Delete", "No"),
    "has_similar_biological_activity_as": ("Match", "similar_to"),
    "upregulated_for": ("Match", "increases"),
    "identified_in": ("Match", "located_in"),
    "not_affects": ("Delete", "No"),
    "encapsulated_in": ("Match", "located_in"),
    "does_not_activate": ("Delete", "No"),
    "re-sensitizes": ("Match", "restores"),
    "perturbs": ("Match", "disrupts"),
    "used_as_surrogate_for": ("Match", "associated_with"),
    "demonstrated_as": ("Match", "defined_as"),
    "synergistically_enhances": ("Match", "enhances"),
    "diverges_from": ("Match", "distinct_from"),
    "designed_using": ("Match", "associated_with"),
    "evaluated_by": ("Reverse", "help_identify"),
    "imparts": ("Match", "provides"),
    "translocates": ("Match", "migrates_to"),
    "is_extremely_rare": ("Delete", "No"),
    "selected_as": ("Match", "defined_as"),
    "is_form_of": ("Match", "hyponym_of"),
    "susceptible_to": ("Reverse", "increases_risk_of"),
    "activated_with": ("Reverse", "activates"),
    "have_prevalence_of": ("Delete", "No"),
    "population_for": ("Match", "associated_with"),
    "circulates_in": ("Match", "located_in"),
    "enhanced_by": ("Reverse", "enhances"),
    "controls_for": ("Match", "associated_with"),
    "may provide": ("Match", "provides"),
    "combines_with": ("Match", "cooperates_with"),
    "location_of": ("Reverse", "located_in"),
    "transported_via": ("Match", "delivers"),
    "stored_at": ("Match", "associated_with"),
    "crosses": ("Match", "enters"),
    "solves": ("Match", "improves"),
    "untightens": ("Match", "disrupts"),
    "has_high_specificity": ("Delete", "No"),
    "has_high_sensitivity": ("Delete", "No"),
    "costimulates": ("Match", "stimulates"),
    "does_not_inhibit": ("Delete", "No"),
    "not mediated by": ("Delete", "No"),
    "has_little_effect_on": ("Delete", "No"),
    "transfers_LPS_to": ("Match", "delivers"),
    "negatively_impacts": ("Match", "impairs"),
    "potential treatment for": ("Match", "treatment_for"),
    "added_to": ("Match", "integrates"),
    "applies_to": ("Match", "associated_with"),
    "duration_for": ("Delete", "No"),
    "connected_with": ("Match", "associated_with"),
    "circulating_in": ("Match", "located_in"),
    "does_not_induce": ("Delete", "No"),
    "temporal_marker_for": ("Match", "help_identify"),
    "evaluation_timepoint_for": ("Match", "associated_with"),
    "superior_for": ("Match", "outperforms"),
    "discussed_in": ("Match", "associated_with"),
    "response_to": ("Match", "responds_to"),
    "phagocytose": ("Match", "endocytoses"),
    "tumor_forming": ("Match", "associated_with"),
    "are_auxotrophic_for": ("Match", "requires"),
    "up_regulates": ("Match", "increases"),
    "mutated_in": ("Match", "associated_with"),
    "is_associated_with": ("Match", "associated_with"),
    "adjunct_therapy_for": ("Match", "treatment_for"),
    "analyzed_through": ("Reverse", "help_identify"),
    "delivered_to": ("Match", "delivers"),
    "fails to suppress": ("Delete", "No"),
    "holds_promise_as": ("Match", "associated_with"),
    "attracts": ("Match", "recruits"),
    "prognostic_marker_for": ("Match", "help_identify"),
    "contradicts": ("Match", "distinct_from"),
    "downregulated_in": ("Reverse", "decreases"),
    "infection_of": ("Match", "infects"),
    "obtained_from": ("Match", "hyponym_of"),
    "is_component_of": ("Match", "hyponym_of"),
    "nucleates": ("Match", "triggers"),
    "recognized_by": ("Reverse", "recognizes"),
    "less_invasive_than": ("Match", "outperforms"),
    "has_high_variation": ("Delete", "No"),
    "has_low_variation": ("Delete", "No"),
    "bacteriostatic_for": ("Match", "inhibits"),
    "varies_across": ("Match", "associated_with"),
    "fails_to_prevent": ("Delete", "No"),
    "synergistically_with": ("Match", "cooperates_with"),
    "over_expressed_in": ("Reverse", "expresses"),
    "stimulation": ("Match", "stimulates"),
    "colonises": ("Match", "located_in"),
    "differentially_depends_on": ("Match", "depends_on"),
    "enables_discrimination_of": ("Match", "help_identify"),
    "synergistically combined with": ("Match", "cooperates_with"),
    "synergistically_promotes": ("Match", "promotes"),
    "recognized_in": ("Match", "located_in"),
    "is_responsible_for": ("Match", "results_in"),
    "chemoattracted_to": ("Match", "migrates_to"),
    "infection_model_for": ("Match", "associated_with"),
    "may_elicit": ("Match", "triggers"),
    "subjected_to": ("Match", "associated_with"),
    "absorbed_via": ("Match", "associated_with"),
    "transcytosis": ("Match", "associated_with"),
    "intersects_with": ("Match", "associated_with"),
    "knock_down": ("Match", "decreases"),
    "augmented_by": ("Reverse", "enhances"),
    "stratified_by": ("Match", "associated_with"),
    "measured_at": ("Reverse", "help_identify"),
    "not_rescued_by": ("Delete", "No"),
    "reacts_against": ("Match", "responds_to"),
    "specific_for": ("Match", "targets"),
    "used_to_identify": ("Match", "help_identify"),
    "used_to_predict": ("Match", "help_identify"),
    "does_not_mimic": ("Delete", "No"),
    "does_not_amplify_in_vivo": ("Delete", "No"),
    "co-cultured_with": ("Match", "associated_with"),
    "disconnected_from": ("Match", "distinct_from"),
    "applied_in": ("Match", "associated_with"),
    "opposes": ("Match", "inhibits"),
    "location_for": ("Reverse", "located_in"),
    "more_frequent_in": ("Reverse", "increases"),
    "efflux_via": ("Match", "associated_with"),
    "essential_in": ("Reverse", "requires"),
    "phosphorylated_by": ("Reverse", "phosphorylates"),
    "derives_sEVs": ("Match", "produces"),
    "cross_reacts_with": ("Match", "binds_to"),
    "vehicle_for": ("Match", "delivers"),
    "directly contributes to": ("Match", "promotes"),
    "decreased_level": ("Match", "decreases"),
    "not_treatment_for": ("Delete", "No"),
    "not_sustained_in": ("Delete", "No"),
    "prevented_by": ("Reverse", "prevents"),
    "removes": ("Match", "eliminates"),
    "not_significant_reservoir_in": ("Delete", "No"),
    "less_effective_for": ("Match", "associated_with"),
    "membrane-binding": ("Match", "binds_to"),
    "synergistic_effect_with": ("Match", "cooperates_with"),
    "meets": ("Match", "associated_with"),
    "leverages": ("Match", "depends_on"),
    "used_for_validation": ("Match", "help_identify"),
    "is_substrate_of": ("Reverse", "decomposes"),
    "anchored_in": ("Match", "located_in"),
    "protrudes_into": ("Match", "enters"),
    "experimental_treatment_for": ("Match", "treatment_for"),
    "suggests": ("Match", "help_identify"),
    "imposes": ("Match", "results_in"),
    "fails_to_rescue": ("Delete", "No"),
    "is_effect_of": ("Reverse", "results_in"),
    "functionally_corresponds_to": ("Match", "similar_to"),
    "better_model_for": ("Match", "similar_to"),
    "does not improve": ("Delete", "No"),
    "not_prevent": ("Delete", "No"),
    "integrates_into": ("Match", "integrates"),
    "poses_challenge_for": ("Match", "impairs"),
    "partially_replaces": ("Match", "replaces"),
    "has_high_mortality_rate": ("Delete", "No"),
    "metabolized_by": ("Reverse", "decomposes"),
    "excreted_via": ("Match", "associated_with"),
    "negatively correlated with": ("Match", "negatively_correlated_with"),
    "has_manifestation": ("Reverse", "help_identify"),
    "has_compromised_inhibition_of": ("Delete", "No"),
    "knocks down": ("Match", "decreases"),
    "has_terminal_half_life": ("Delete", "No"),
    "has_apparent_volume_of_distribution": ("Delete", "No"),
    "causative_pathogen_of": ("Match", "results_in"),
    "converted_into": ("Match", "converts"),
    "administered_to": ("Match", "delivers"),
    "less costly than": ("Match", "outperforms"),
    "resists": ("Match", "resistant_to"),
    "is_ligand_for": ("Match", "binds_to"),
    "averts": ("Match", "prevents"),
    "when_effective_for": ("Match", "associated_with"),
    "has_weight": ("Delete", "No"),
    "has_active": ("Delete", "No"),
    "exposure_for": ("Match", "associated_with"),
    "homologous_to": ("Match", "similar_to"),
    "infection_model_in": ("Match", "associated_with"),
    "detoxifies": ("Match", "neutralizes"),
    "persists_for": ("Delete", "No"),
    "mechanism_for": ("Match", "mediates"),
    "generated_in": ("Reverse", "produces"),
    "converges_with": ("Match", "integrates"),
    "transactivates": ("Match", "activates"),
    "resets": ("Match", "restores"),
    "not decreases": ("Delete", "No"),
    "is driver of": ("Match", "promotes"),
    "is required for": ("Reverse", "requires"),
    "is strategy for": ("Match", "associated_with"),
    "may_have_influence_on": ("Match", "affects"),
    "potential_source_for": ("Match", "produces"),
    "internalizes_in": ("Match", "associated_with"),
    "differentially_affects": ("Match", "affects"),
    "formulated_in": ("Match", "associated_with"),
    "cross-protective_effect_against": ("Match", "protects"),
    "more potent than": ("Match", "outperforms"),
    "is_low": ("Delete", "No"),
    "represents": ("Match", "defined_as"),
    "initiated_from": ("Reverse", "triggers"),
    "has_threshold": ("Delete", "No"),
    "does_not_detect": ("Delete", "No"),
    "well-tolerated": ("Delete", "No"),
    "has_higher_degranulation_ability_than": ("Match", "outperforms"),
    "not_significantly_affects": ("Delete", "No"),
    "digests": ("Match", "decomposes"),
    "potential_therapeutic_target": ("Match", "associated_with"),
    "unable_to": ("Delete", "No"),
    "binding_residue_in": ("Match", "located_in"),
    "equivalent_to": ("Match", "similar_to"),
    "possesses": ("Match", "includes"),
    "phylogenetically_related_to": ("Match", "similar_to"),
    "has_higher_growth_rate_than": ("Match", "outperforms"),
    "less_efficient_than": ("Reverse", "outperforms"),
    "survives_for": ("Delete", "No"),
    "evolutionary_link_between": ("Match", "associated_with"),
    "indirectly_inhibits": ("Match", "inhibits"),
    "donor_for": ("Match", "provides"),
    "recipient_for": ("Reverse", "provides"),
    "benchmark_against": ("Match", "associated_with"),
    "co-localizes_with": ("Match", "co-occurs_with"),
    "down-regulated_in": ("Reverse", "decreases"),
    "recovers_to_baseline": ("Match", "restores"),
    "penetrates": ("Match", "enters"),
    "more_effective_against": ("Match", "outperforms"),
    "less_effective_against": ("Reverse", "outperforms"),
    "has_stronger_induction_of": ("Match", "induces"),
    "serves_as_target_for": ("Reverse", "targets"),
    "most_sensitive_to": ("Match", "responds_to"),
    "least_sensitive_to": ("Match", "associated_with"),
    "measured_in": ("Reverse", "help_identify"),
    "has_bacteriostatic_effect": ("Match", "inhibits"),
    "used_in_cytotoxicity_assay": ("Match", "associated_with"),
    "address": ("Match", "associated_with"),
    "does not promote": ("Delete", "No"),
    "has antitumor role in": ("Match", "treatment_for"),
    "contamination_in": ("Match", "located_in"),
    "silences": ("Match", "inhibits"),
    "occurs_before": ("Match", "outperforms"),
    "co-occur_with": ("Match", "co-occurs_with"),
    "evades": ("Match", "associated_with"),
    "model_of": ("Match", "similar_to"),
    "deregulation_causes": ("Match", "results_in"),
    "dominates": ("Match", "outperforms"),
    "advances": ("Match", "promotes"),
    "has_excellent": ("Delete", "No"),
    "has_size": ("Delete", "No"),
    "has_zeta_potential": ("Delete", "No"),
    "counterbalances": ("Match", "neutralizes"),
    "differentially_regulates": ("Match", "regulates"),
    "reduces_steps_compared_to": ("Match", "outperforms"),
    "discovers": ("Match", "help_identify"),
    "better_sample_for": ("Match", "outperforms"),
    "not_improve": ("Delete", "No"),
    "has_high_specificity_for": ("Match", "targets"),
    "inoculated_into": ("Match", "enters"),
    "unaffected_by": ("Delete", "No"),
    "synergistically_kills": ("Match", "kills"),
    "used_to_generate": ("Match", "produces"),
    "prolonged_in": ("Reverse", "prolongs"),
    "primary_endpoint_of": ("Match", "associated_with"),
}


def main() -> int:
    """主入口：解析参数，读取输入 CSV，输出映射后的 CSV。"""
    parser = argparse.ArgumentParser(
        description="将非预定义关系类型映射到预定义关系类型（Match/Reverse/Delete）"
    )
    parser.add_argument(
        "--input", "-i", required=True,
        help="输入 CSV 文件路径（包含 relation,count 两列的非预定义关系统计文件）"
    )
    parser.add_argument(
        "--output", "-o", required=True,
        help="输出 CSV 文件路径"
    )
    args = parser.parse_args()

    input_path = Path(args.input)
    output_path = Path(args.output)

    # 读取非预定义关系
    rows_in = []
    with input_path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows_in.append(row["relation"])

    # 校验映射字典覆盖情况
    missing = [r for r in rows_in if r not in RELATION_MAP]
    if missing:
        print(f"[警告] 共有 {len(missing)} 个关系未在映射字典中找到：", file=sys.stderr)
        for r in missing[:20]:
            print(f"  - {r}", file=sys.stderr)
        return 1

    # 校验映射目标是否在预定义集合中（以 Triple_prompt_v2.md 为准）
    invalid_targets = []
    for r in rows_in:
        m_type, m_rel = RELATION_MAP[r]
        if m_type in {"Match", "Reverse"} and m_rel not in PREDEFINED_RELATIONS:
            invalid_targets.append((r, m_type, m_rel))
    if invalid_targets:
        print(f"[警告] 共有 {len(invalid_targets)} 个映射目标不在预定义集合中：", file=sys.stderr)
        for item in invalid_targets[:20]:
            print(f"  - {item}", file=sys.stderr)
        return 1

    # 写入输出文件
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["relation", "matching_manual_type", "matching_manual_relation"])
        for r in rows_in:
            m_type, m_rel = RELATION_MAP[r]
            writer.writerow([r, m_type, m_rel])

    # 统计输出
    total = len(rows_in)
    n_match = sum(1 for r in rows_in if RELATION_MAP[r][0] == "Match")
    n_reverse = sum(1 for r in rows_in if RELATION_MAP[r][0] == "Reverse")
    n_delete = sum(1 for r in rows_in if RELATION_MAP[r][0] == "Delete")
    print(f"[完成] 共处理 {total} 个非预定义关系：")
    print(f"  - Match  : {n_match}")
    print(f"  - Reverse: {n_reverse}")
    print(f"  - Delete : {n_delete}")
    print(f"[输出] {output_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
